version: 0.2

phases:
  install:
    commands:
      - echo "Running build setup (install phase)"
      - chmod +x build-setup.sh
      - ./build-setup.sh

  build:
    commands:
      - echo "Starting SBOM Graviton Compatibility Analysis"
      - chmod +x build-validation.sh
      - ./build-validation.sh