# Checkov configuration file
# This file suppresses specific security findings that require architectural decisions
# or are not applicable to the current deployment model

# Global configuration
framework:
  - terraform

# Skip specific checks with justifications
skip-check:
  # S3 Lifecycle Configuration - Multipart Upload Cleanup
  # These are already implemented but still flagged - may be a checkov detection issue
  - CKV_AWS_300  # Ensure S3 lifecycle configuration sets period for aborting failed uploads

  # Lambda VPC Configuration
  # Suppressed: Lambda function doesn't require VPC access for this use case
  # The function only needs to trigger CodePipeline and doesn't access VPC resources
  - CKV_AWS_117  # Ensure that AWS Lambda function is configured inside a VPC

  # Lambda Code Signing
  # Suppressed: Code signing requires additional infrastructure setup and signing process
  # Consider implementing in production environments with higher security requirements
  - CKV_AWS_272  # Ensure AWS Lambda function is configured to validate code-signing

  # S3 Cross-Region Replication
  # Suppressed: Cross-region replication requires additional infrastructure and costs
  # Not required for this demo/development environment
  - CKV_AWS_144  # Ensure that S3 bucket has cross-region replication enabled

# Optional: Specify directories to scan (if you want to limit scope)
# directory:
#   - "."

# Optional: Exclude specific directories
# skip-path:
#   - "node_modules"
#   - ".terraform"

# Optional: Set severity threshold
# check-threshold: HIGH

# Optional: Output format
# output: cli

# Optional: Quiet mode (reduce output verbosity)
# quiet: true