# Backend configuration for Terraform state
# This file is dynamically generated by the CI/CD pipeline
# For local development, you can either:
# 1. Use local state (comment out or delete this file)
# 2. Configure your own S3 backend below

# Uncomment and configure the following for local development with remote state:
/*
terraform {
  backend "s3" {
    bucket         = "your-terraform-state-bucket"
    key            = "sbom-graviton-app-dependency-compatibility-tool/terraform.tfstate"
    region         = "us-east-2"
    encrypt        = true
    dynamodb_table = "your-terraform-lock-table"
  }
}
*/