data "aws_caller_identity" "current" {}
data "aws_region" "current" {}
data "archive_file" "zip_trigger" {
  type        = "zip"
  source_dir  = "${path.module}/functions/trigger/"
  output_path = "${path.module}/functions/packaged/trigger.zip"
}

data "archive_file" "zip_validation_tool" {
  type        = "zip"
  source_dir  = "${path.module}/src/sbom-graviton-app-dependency-compatibility-tool/"
  output_path = "${path.module}/src/packaged/script.zip"

  # Add explicit depends_on to ensure archive is created before being referenced
  depends_on = [
    # This ensures any files that might be generated by other resources are ready
    # before the archive is created
  ]
}
